name: Auto Merge PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Merge PR
        uses: devops-infra/action-pull-request@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: 'merge'
